config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  resources :books
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :profile_image
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :user_id, presence: true

   def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
   end

   def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
   end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    @books = Book.all
    @user = current_user
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @book.user = current_user
  end

  def edit
    @book = Book.find(params[:id])
    @book.user = current_user
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to book_path(@book.id)
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    @user = current_user
    redirect_to user_path(current_user.id)
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: "form-control book_body" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
    <tr>
      <td><%= link_to book.user do %>
        <%= image_tag book.user.get_profile_image(40, 40) %>
        <% end %>
      </td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
    </tr>
   <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Edit Book</h1>
      <%= form_with model: @book do |f| %>
      <div class="form-group">
        <label class="book_title">Title</label>
        <%= f.text_field :title, class: 'form-control book_title' %>
      </div>
      <div class="form-group">
        <label class="book_opinion">Opinion</label>
        <%= f.text_area :body, class: 'form-control book_body' %>
      </div>
    </div>
  <div class="form-group">
    <%= f.submit 'Update Book', class: 'btn btn-success' %>
  </div>
  <% end %>
   <%= link_to 'Show', @book, class: "book_#{@book.id}" %>
   <%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <h2 class="mt-3">New Book</h2>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <h2>New Book</h2>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tr>
          <td><%= link_to @book.user do %>
           <%= image_tag @book.user.get_profile_image(40, 40) %>
           <%= @book.user.name %>
           <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <% if @boo.user == current_user %>
           <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success edit_book" %></td>
           <td><%= link_to "Destroy", book_path(@book.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book" %></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>
        welcome to
        <strong>Boookers</strong>
        !!
      </h1>
      <p>
        In
        <strong>Bookers</strong>
        ,
      </p>
      <p>you can share and exchange your opininons, inpressions, and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksStory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
     <tr>
       <td>
         <%= link_to user do %>
         <%= image_tag user.get_profile_image(40, 40) %>
         <% end %>
       </td>
       <td><%= user.name %></td>
       <td><%= link_to "Show", user, class: "user_{user.id}" %></td>
     </tr>
  </tbody>
</table>

app/views/users/_info.html.erb
<%= image_tag user.get_profile_image(63, 63), class: "attachment user profile_image fallback" %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

<div class="row">
  <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
       <div class="form-group">
         <label for="user_name">Name</label>
         <%= f.file_field :name, autofocus: true, id: "user_name", placeholder: "名前", class: "form-control name" %>
       </div>
       <div class="form-group">
         <label for="user_image">Image</label>
         <%= f.file_field :profile_image, placeholder: "プロフィール画像", class: "form-control-file user_image", accept: "image/*" %>
       </div>
       <div class="form-group">Introduction</div>
       <%= f.text_area :introduction, placeholder: "自己紹介文", class: "form-control introduction" %>
       <div class="form-group">
         <%= f.submit "Update User", class: "btn btn-secondary" %>
       </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
       <%= image_tag @user.get_profile_image(63, 63), class: "attachment user profile_image fallback" %>
        <table class="table">
          <tbody>
            <tr></tr>
            <ty>
             <th>name</th>
             <th><%= @user.name %></th>
            </ty>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>books</h2>
      <%= render 'books/index', books: @books %>
    </div>
  </div>
</div>